travis:
  secure:
    BINSTAR_TOKEN: I0u2BqPF30rN4SuBDEh2Z6zlWxiDA0pUUgbaQnkBzzmzJbmbeaJIyP/6CrJTB/OFpPGK9viHVYuZ5r7+Z+UW9aXFzvdn6/nYDjCAGuyAYSUHIeRdYvKLLU4Re8Uc1DfNhj1qRwuIcgquv31Sw6x9sM00bivpPSJsCPhIqSAbXEseJ2Jfys+I8Qv8bt2cat0uvXAimpcbBjwRwMFGUhXGRSOmOD5JbdIzY8gt6E76vV0mNTFiCnscCU92ca9g2DQukPxtthX238YXOtibezAunpvECI0MjQ/iphWOkO6rkVbohainDu8OnU+EkS11Fd3DJ25PgvNV4JLFPumpHHLqqUgUUeqdIpkcXGDX+TfZ8IOv1XmLt5vu+IJONP3pvit84aHE8P2c533255lxb1V5RJkTJmu3mr3eFN+bDSLJqGGbBuyG9/JmNPwnd0435r101n14zsCxCuSjm6miLDsc+DabapXoapllbYdVGTsiyGBKyabNMbmsOSDTHMQSvBmh+s7RxIsCI8Gx2nkR4iJeSsWAiLG4X8dtdm2s/WlCAbIUdoWElRrERPrp9geiGMTiXCezgVjhSRoJARsRROR+g4FJcnnuvH21eVe2iVbl3vSG1/ObiHMMvDG5SGTfMxsa6JEu8Fwi1+Sw68xfOUwzoBfPWacKOYdlvrACLu8jWtc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
